sudo: false
language: java
cache:
  directories:
  - $HOME/.m2
install: true
script:
  - mvn clean test -Dmaven.test.redirectTestOutputToFile=true
  - mvn jacoco:report
branches:
  only:
  - develop
jdk:
  - openjdk9

after_success:
  - bash <(curl -s https://codecov.io/bash)