sudo: false
language: java
cache:
  directories:
  - $HOME/.m2
install: true
script: mvn clean package -B -DskipTests 
#TODO: enable tests!!! -q -Djava.util.logging.config.file=${basedir}/.travis-logging.properties -Dmaven.test.failure.ignore=true
branches:
  only:
  - 2.2.x
#jdk:
#  - openjdk8
